version: "3"

services:
  web: 
    build:
      context: .
      dockerfile: docker/dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DATABASE_DSN=postgres://postgres:password@postgres:5432/seccamp

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=seccamp
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
