FROM golang:1.20-alpine AS builder
WORKDIR /app
ADD . /app/
RUN go mod tidy
RUN go build -o main ./cmd/server/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
CMD ["./main"]
EXPOSE 8080